export const data = new webix.DataCollection({ 
	
	data:[
	
			{ id:1,  Product:"BOROFONE WIRELESS POWERBANK BT16 10000 MAH",                     Quantity:"500", UoM:"pcs", Price:"298.000"},
			{ id:2,  Product:"BOROFONE POWERBANK 10000 MAH BT19",                              Quantity:"500", UoM:"pcs", Price:"166.000"},
			{ id:3,  Product:"FOLDING PHONE & TABLET HOLDER DESKTOP",                          Quantity:"500", UoM:"pcs", Price:"19.000"},
			{ id:4,  Product:"FOOMEE ADAPTER CA61",                                            Quantity:"500", UoM:"pcs", Price:"99.000"},
			{ id:5,  Product:"FOOMEE DATA CABLE DD10",                                         Quantity:"500", UoM:"pcs", Price:"39.000"},
			{ id:6,  Product:"FOOMEE DATA CABLE NI10",                                         Quantity:"500", UoM:"pcs", Price:"59.000"},
			{ id:7,  Product:"FOOMEE DATA CABLE NM10",                                         Quantity:"500", UoM:"pcs", Price:"59.000"},
			{ id:8,  Product:"FOOMEE KABEL DATA NR10",                                         Quantity:"500", UoM:"pcs", Price:"37.000"},
			{ id:9,  Product:"FOOMEE KABEL DATA NZ20",                                         Quantity:"500", UoM:"pcs", Price:"59.000"},
			{ id:10, Product:"FOOMEE 5000MAH POWERBANK AA05",                                  Quantity:"500", UoM:"pcs", Price:"110.000"},
			{ id:11, Product:"FOOMEE 10000MAH POWERBANK AB10",                                 Quantity:"500", UoM:"pcs", Price:"259.000"},
			{ id:12, Product:"FOOMEE 5000MAH POWERBANK AC05",                                  Quantity:"500", UoM:"pcs", Price:"169.000"},
			{ id:13, Product:"FOOMEE 6600MAH POWERBANK AC06S",                                 Quantity:"500", UoM:"pcs", Price:"149.000"},
			{ id:14, Product:"FOOMEE 10000MAH POWERBANK AC10",                                 Quantity:"500", UoM:"pcs", Price:"229.000"},
			{ id:15, Product:"FOOMEE 5000 MAH POWERBANK AD05",                                 Quantity:"500", UoM:"pcs", Price:"159.000"},
			{ id:16, Product:"FOOMEE 10000 MAH POWERBANK AR10",                                Quantity:"500", UoM:"pcs", Price:"249.000"},
			{ id:17, Product:"FOOMEE HEADSET QA17",                                            Quantity:"500", UoM:"pcs", Price:"59.000"},
			{ id:18, Product:"FOOMEE KABEL SA10",                                              Quantity:"500", UoM:"pcs", Price:"49.000"},
			{ id:19, Product:"FOOMEE KABEL DATA SN10",                                         Quantity:"500", UoM:"pcs", Price:"99.000"},
			{ id:20, Product:"GEL PAD PHONE HOLDER NANO TECHNOLOGY",                           Quantity:"500", UoM:"pcs", Price:"9.900"},
			{ id:21, Product:"HIPPO ELITE WIRELESS DESKTOP CHARGING LEV 10 W",                 Quantity:"500", UoM:"pcs", Price:"199.000"},
			{ id:22, Product:"HIPPO ELITE POWER DELIVERY 18WATT PRIME 12000 MAH",              Quantity:"500", UoM:"pcs", Price:"499.000"},
			{ id:23, Product:"HIPPO ELITE CAR CHARGER 42 WATT SV1",                            Quantity:"500", UoM:"pcs", Price:"299.000"},
			{ id:24, Product:"HIPPO ELITE OTHELLO 3 GEN 2 10000 MAH WIRELESS POWERBANK",       Quantity:"500", UoM:"pcs", Price:"599.000"},
			{ id:25, Product:"HIPPO QUICK CHARGE 3.0 (30W) ARK 2 ADAPTOR",                     Quantity:"500", UoM:"pcs", Price:"99.000"},
			{ id:26, Product:"HIPPO QUICK CHARGE 3.0 (30W) ARK 3 ADAPTOR",                     Quantity:"500", UoM:"pcs", Price:"109.000"},
			{ id:27, Product:"HIPPO POWER DELIVERY (18W) DYNAMIC ADAPTOR",                     Quantity:"500", UoM:"pcs", Price:"109.000"},
			{ id:28, Product:"HIPPO CAR CHARGER FANTASTIC QUICK CHARGE",                       Quantity:"500", UoM:"pcs", Price:"79.000"},
			{ id:29, Product:"HIPPO PHONE HOLDER HALTER 02",                                   Quantity:"500", UoM:"pcs", Price:"59.000"},
			{ id:30, Product:"HIPPO 10000 MAH POWERBANK ORBIT",                                Quantity:"500", UoM:"pcs", Price:"189.000"},
			{ id:31, Product:"HIPPO PD2 QC 3.0 10000 MAH POWERBANK OUTLANDER",                 Quantity:"500", UoM:"pcs", Price:"209.000"},
			{ id:32, Product:"HIPPO QUICK CHARGE 3.0 (18W) RAPID 1 ADAPTOR",                   Quantity:"500", UoM:"pcs", Price:"89.000"},
			{ id:33, Product:"HOCO WIRELESS CHARGING 8000 MAH B32 POWERBANK",                  Quantity:"500", UoM:"pcs", Price:"351.000"},
			{ id:34, Product:"HOCO ULTRA THIN POWERBANK B35D 5000 MAH",                        Quantity:"500", UoM:"pcs", Price:"102.000"},
			{ id:35, Product:"HOCO FAST CHARGER C51A DUAL USB PORT",                           Quantity:"500", UoM:"pcs", Price:"71.000"},
			{ id:36, Product:"HOCO STRONG MOUNT CA40 HANDPHONE HOLDER",                        Quantity:"500", UoM:"pcs", Price:"67.000"},
			{ id:37, Product:"HOCO PORTABLE CHARGING DOCK 5W CW13 WIRELESS",                   Quantity:"500", UoM:"pcs", Price:"104.000"},
			{ id:38, Product:"HOCO ROUND TABLETOP CHARGING CW14 WIRELESS",                     Quantity:"500", UoM:"pcs", Price:"137.000"},
			{ id:39, Product:"HOCO WIRELESS CHARGER CW6 ROUND PAD QI",                         Quantity:"500", UoM:"pcs", Price:"173.000"},
			{ id:40, Product:"HOCO GAMING HOLDER GAMEPAD GM2",                                 Quantity:"500", UoM:"pcs", Price:"141.000"},
			{ id:41, Product:"MOBILE KIOSK CABLE MICRO ARMOR",                                 Quantity:"500", UoM:"pcs", Price:"135.000"},
			{ id:42, Product:"MOBILE KIOSK CABLE IPHONE ARMOR",                                Quantity:"500", UoM:"pcs", Price:"150.000"},
			{ id:43, Product:"Mobile Kiosk Bluetooth Connector",                               Quantity:"500", UoM:"pcs", Price:"199.900"},
			{ id:44, Product:"Mobile Kiosk Braided 2A Usb Cable For Android",                  Quantity:"500", UoM:"pcs", Price:"32.900"},
			{ id:45, Product:"Mobile Kiosk Braided 2A Usb Cable Type C",                       Quantity:"500", UoM:"pcs", Price:"34.900"},
			{ id:46, Product:"Mobile Kiosk Braided 2A Usb Lightning Cable For Iphone",         Quantity:"500", UoM:"pcs", Price:"34.900"},
			{ id:47, Product:"MOBILE KIOSK 3IN1 CABLE",                                        Quantity:"500", UoM:"pcs", Price:"120.000"},
			{ id:48, Product:"Mobile Kiosk Power Bank Mk L6000",                               Quantity:"500", UoM:"pcs", Price:"157.000"},
			{ id:49, Product:"MOBILE KIOSK USB CABLE ANDROID PREMIER",                         Quantity:"500", UoM:"pcs", Price:"70.000"},
			{ id:50, Product:"MOBILE KIOSK USB CABLE TYPE C PREMIER",                          Quantity:"500", UoM:"pcs", Price:"90.000"},
			{ id:51, Product:"MOBILE KIOSK USB CABLE IPHONE PREMIER",                          Quantity:"500", UoM:"pcs", Price:"90.000"},
			{ id:52, Product:"MOBILE KIOSK ACCESSORIES RING & DOCK",                           Quantity:"500", UoM:"pcs", Price:"45.000"},
			{ id:53, Product:"Mobile Kiosk Ring & Holder",                                     Quantity:"500", UoM:"pcs", Price:"39.900"},
			{ id:54, Product:"Mobile Kiosk Stereo Earphone MK 552",                            Quantity:"500", UoM:"pcs", Price:"80.000"},
			{ id:55, Product:"OASE POWER BANK A20",                                            Quantity:"500", UoM:"pcs", Price:"399.000"},
			{ id:56, Product:"OASE CAR CHARGER C2",                                            Quantity:"500", UoM:"pcs", Price:"59.000"},
			{ id:57, Product:"OASE CAR CHARGER C5",                                            Quantity:"500", UoM:"pcs", Price:"99.000"},
			{ id:58, Product:"OASE CAR CHARGER C6",                                            Quantity:"500", UoM:"pcs", Price:"129.000"},
			{ id:59, Product:"OASE CABLE DATA M8F",                                            Quantity:"500", UoM:"pcs", Price:"49.000"},
			{ id:60, Product:"OASE CABLE DATA M8FC",                                           Quantity:"500", UoM:"pcs", Price:"49.000"},
			{ id:61, Product:"OASE CABLE DATA MP-1C",                                          Quantity:"500", UoM:"pcs", Price:"39.000"}
		
	]
});